apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: product
        image: gogoacr.azurecr.io/product-api:latest
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        env:
          - name: ASPNETCORE_URLS
            value: http://+:7100
        ports:
        - containerPort: 7100
          name: product
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  ports:
  - port: 7100
  selector:
    app: product
