# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  gogoproductapi:
    image: product-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7100:7100
