# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  gogoproductapi:
    image: gogoproductapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7100:7100
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
